# Generated by Django 5.2.4 on 2025-07-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réclamation', 'verbose_name_plural': 'Réclamations'},
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
