# Generated by Django 5.2.4 on 2025-07-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_wilaya_alter_municipality_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AddField(
            model_name='municipality',
            name='delegation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
