# Generated by Django 5.2.4 on 2025-07-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_municipality_options_municipality_delegation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='claim',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='claim',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.municipality', verbose_name='Municipalité concernée'),
        ),
    ]
