# Generated by Django 5.2.4 on 2025-07-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_location_lat_claim_location_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
